CONFIG_NAME: 'MirrorGAN'
DATASET_NAME: 'comp_birds'
DATA_DIR: '/home/seth/code/MirrorGAN/data/birds'
GPU_ID: 0
WORKERS: 4
OUTPUT_PATH: '/data/seth/MirrorGAN'
TREE:
    BRANCH_NUM: 3

TRAIN:
    FLAG: True
    NET_G: ''
    B_NET_D: True
    BATCH_SIZE: 12  # 22
    MAX_EPOCH: 300
    SNAPSHOT_INTERVAL: 50
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002

    NET_E: '/home/seth/code/MirrorGAN/data/STEM/bird/text_encoder.pth'
    SMOOTH:
        GAMMA1: 4.0  # 1,2,5 good 4 best  10&100bad
        GAMMA2: 5.0
        GAMMA3: 10.0  # 10good 1&100bad
        LAMBDA: 0.0
        LAMBDA1: 10.0

CAP:
    embed_size: 256
    hidden_size: 256
    num_layers: 1
    learning_rate: 0.001
    caption_cnn_path: '/data/seth/MirrorGAN/output/birds_STREAM_2020_07_23_12_11_07/Model/encoder-50.ckpt'
    caption_rnn_path: '/data/seth/MirrorGAN/output/birds_STREAM_2020_07_23_12_11_07/Model/decoder-50.ckpt'

GAN:
    DF_DIM: 64
    GF_DIM: 32
    Z_DIM: 100
    R_NUM: 2

TEXT:
    EMBEDDING_DIM: 256
    CAPTIONS_PER_IMAGE: 10
